// Enhanced PDF export with branding, header, and pagination for amortization
// Ensure these are installed: npm i jspdf html2canvas
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Bank-style EMI Calculator PDF Export
 * Professional loan summary matching bank sanction letter format
 */
export async function exportEMIPDF(data, options = {}) {
  const {
    includeAmortization = false,
    includeAdvancedAnalysis = true
  } = options;

  const pdf = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  // Helper function to format currency for PDF (handles raw numbers)
  const formatPDFCurrency = (value) => {
    // Handle null/undefined
    if (value === null || value === undefined) return 'Rs. 0.00';
    
    // If already a number, use directly
    let numValue = typeof value === 'number' ? value : parseFloat(String(value).replace(/[₹Rs.,\s]/g, ''));
    
    // Validate
    if (isNaN(numValue) || !isFinite(numValue)) return 'Rs. 0.00';
    
    // Format with Indian number system (lakhs, crores)
    const formatted = numValue.toLocaleString('en-IN', {
      maximumFractionDigits: 2,
      minimumFractionDigits: 2
    });
    
    return `Rs. ${formatted}`;
  };

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace) => {
    if (yPos + requiredSpace > pageHeight - margin - 30) {
      pdf.addPage();
      yPos = margin;
      return true;
    }
    return false;
  };

  // Helper function for footer
  const addFooter = (pageNum) => {
    pdf.setFontSize(8);
    pdf.setTextColor(120, 120, 120);
    pdf.text(
      `Page ${pageNum} | Generated by VegakTools.com`,
      pageWidth / 2,
      pageHeight - 20,
      { align: 'center' }
    );
  };

  // ============================================
  // 1️⃣ HEADER SECTION
  // ============================================
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(102, 126, 234); // Brand color
  pdf.text('Loan EMI Calculation Summary', margin, yPos);
  yPos += 25;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  const loanTypeMap = {
    home: 'Home Loan',
    car: 'Car Loan',
    personal: 'Personal Loan',
    education: 'Education Loan'
  };
  pdf.text(`${loanTypeMap[data.loanType] || 'Home Loan'} EMI Report`, margin, yPos);
  yPos += 20;

  pdf.setFontSize(9);
  pdf.setTextColor(120, 120, 120);
  const timestamp = new Date().toLocaleString('en-IN', {
    dateStyle: 'long',
    timeStyle: 'short'
  });
  pdf.text(`Generated on: ${timestamp}`, margin, yPos);
  yPos += 12;

  pdf.setTextColor(102, 126, 234);
  pdf.textWithLink('Calculator: https://vegaktools.com/in/calculators/emi', margin, yPos, {
    url: 'https://vegaktools.com/in/calculators/emi'
  });
  yPos += 25;

  // Separator line
  pdf.setDrawColor(220, 220, 220);
  pdf.setLineWidth(1);
  pdf.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 25;

  // ============================================
  // 1.4 BANK-STYLE SANCTION SUMMARY BOX
  // ============================================
  pdf.setFillColor(248, 250, 252); // Light gray
  pdf.roundedRect(margin, yPos, contentWidth, 110, 5, 5, 'F');
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Loan Summary', margin + 10, yPos + 18);
  
  yPos += 32;
  
  // Summary table with right-aligned values
  pdf.setFontSize(9);
  const summaryRows = [
    ['Loan Amount', formatPDFCurrency(data.loanAmount)],
    ['Tenure', `${Math.round(data.tenure)} Years`],
    ['Interest Rate', `${data.interestRate.toFixed(2)}% p.a. (${data.interestType === 'fixed' ? 'Fixed' : 'Floating'})`],
    ['Monthly EMI', formatPDFCurrency(data.emi)],
    ['Total Interest', formatPDFCurrency(data.totalInterest)],
    ['Total Payable', formatPDFCurrency(data.totalAmount)]
  ];
  
  summaryRows.forEach((row) => {
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(70, 70, 70);
    pdf.text(row[0], margin + 15, yPos);
    
    pdf.text(':', margin + 140, yPos);
    
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 30, 30);
    pdf.text(row[1], margin + 150, yPos);
    
    yPos += 13;
  });
  
  yPos += 15;

  // ============================================
  // 1.5 LOAN SNAPSHOT (Quick Overview)
  // ============================================
  pdf.setFillColor(240, 249, 255); // Light blue background
  pdf.roundedRect(margin, yPos, contentWidth, 50, 5, 5, 'F');
  
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 64, 175); // Blue
  pdf.text('Loan Snapshot:', margin + 10, yPos + 15);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(50, 50, 50);
  // Split into two lines for readability
  const line1 = `${loanTypeMap[data.loanType] || 'Home Loan'} | ${formatPDFCurrency(data.loanAmount)} | ${Math.round(data.tenure)} Years`;
  const line2 = `${data.interestRate.toFixed(2)}% ${data.interestType === 'fixed' ? 'Fixed Rate' : 'Floating Rate'} | Monthly EMI: ${formatPDFCurrency(data.emi)}`;
  pdf.text(line1, margin + 90, yPos + 15);
  pdf.text(line2, margin + 90, yPos + 28);
  
  yPos += 65;

  // ============================================
  // 2️⃣ BORROWER INPUTS SUMMARY (Bank-Style Table)
  // ============================================
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(50, 50, 50);
  pdf.text('Loan Parameters', margin, yPos);
  yPos += 20;

  // Table data
  const inputRows = [
    ['Loan Type', loanTypeMap[data.loanType] || 'Home Loan'],
    ['Loan Amount', formatPDFCurrency(data.loanAmount)],
    ['Interest Rate', `${data.interestRate}% p.a.`],
    ['Loan Tenure', `${data.tenure} Years`],
    ['Interest Type', data.interestType === 'fixed' ? 'Fixed Rate' : 'Floating (Repo-linked)']
  ];

  if (data.moratoriumMonths > 0) {
    inputRows.push(['Moratorium Period', `${data.moratoriumMonths} Months`]);
  }

  // Draw table
  pdf.setFontSize(10);
  const rowHeight = 22;
  const col1Width = 180;

  inputRows.forEach((row, idx) => {
    checkPageBreak(rowHeight);
    
    // Alternate row background
    if (idx % 2 === 0) {
      pdf.setFillColor(248, 250, 252);
      pdf.rect(margin, yPos - 15, contentWidth, rowHeight, 'F');
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(70, 70, 70);
    pdf.text(row[0], margin + 10, yPos);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(30, 30, 30);
    pdf.text(row[1], margin + col1Width, yPos);

    yPos += rowHeight;
  });

  yPos += 15;

  // ============================================
  // 3️⃣ EMI RESULTS SUMMARY (HIGHLIGHT SECTION)
  // ============================================
  checkPageBreak(150);
  
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(50, 50, 50);
  pdf.text('EMI Calculation Results', margin, yPos);
  yPos += 25;

  // Highlighted EMI box with context
  pdf.setFillColor(102, 126, 234);
  pdf.roundedRect(margin, yPos - 15, contentWidth, 70, 5, 5, 'F');
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(255, 255, 255);
  pdf.text('Monthly EMI', margin + 15, yPos);
  
  pdf.setFontSize(26);
  pdf.setFont('helvetica', 'bold');
  pdf.text(formatPDFCurrency(data.emi), margin + 15, yPos + 30);
  
  // Context line
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(255, 255, 255);
  const contextText = data.moratoriumMonths > 0 
    ? `Starts after ${data.moratoriumMonths}-month moratorium | ${data.interestType === 'fixed' ? 'Fixed rate' : 'Floating rate'}`
    : `${data.interestType === 'fixed' ? 'Fixed rate' : 'Floating rate'} | Payable from month 1`;
  pdf.text(contextText, margin + 15, yPos + 48);
  
  yPos += 85;

  // Results grid
  const resultRows = [
    ['Total Interest Payable', formatPDFCurrency(data.totalInterest)],
    ['Total Amount Payable', formatPDFCurrency(data.totalAmount)]
  ];

  pdf.setFontSize(11);
  resultRows.forEach((row) => {
    checkPageBreak(25);
    
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(70, 70, 70);
    pdf.text(row[0], margin + 10, yPos);

    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 30, 30);
    pdf.text(row[1], pageWidth - margin - 10, yPos, { align: 'right' });

    yPos += 25;
  });

  yPos += 10;

  // ============================================
  // 4. MORATORIUM IMPACT (Conditional)
  // ============================================
  if (data.moratoriumMonths > 0 && data.moratoriumInterest > 0) {
    checkPageBreak(140);

    pdf.setFillColor(255, 251, 235); // Light amber background
    pdf.roundedRect(margin, yPos, contentWidth, 120, 5, 5, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(217, 119, 6); // Amber
    pdf.text('[Moratorium Period Impact]', margin + 10, yPos + 20);

    yPos += 40;

    const moratoriumRows = [
      ['Original Principal', formatPDFCurrency(data.originalPrincipal || data.loanAmount)],
      ['Interest Accrued During Moratorium', formatPDFCurrency(data.moratoriumInterest)],
      ['Adjusted Principal', formatPDFCurrency(data.adjustedPrincipal)]
    ];

    pdf.setFontSize(10);
    moratoriumRows.forEach((row) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(70, 70, 70);
      pdf.text(row[0], margin + 15, yPos);

      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 30, 30);
      pdf.text(row[1], pageWidth - margin - 15, yPos, { align: 'right' });

      yPos += 20;
    });

    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(100, 100, 100);
    const noteText = `Note: EMI is calculated on adjusted principal. EMI payments begin after the ${data.moratoriumMonths}-month moratorium period.`;
    const noteLines = pdf.splitTextToSize(noteText, contentWidth - 30);
    pdf.text(noteLines, margin + 15, yPos + 5);

    yPos += 35;
  }

  // ============================================
  // 5. PREPAYMENT IMPACT (Conditional)
  // ============================================
  if (data.yearlyPrepay > 0 && includeAdvancedAnalysis) {
    checkPageBreak(130);

    pdf.setFillColor(236, 253, 245); // Light green background
    pdf.roundedRect(margin, yPos, contentWidth, 110, 5, 5, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(16, 185, 129); // Green
    pdf.text('[Prepayment Impact Summary]', margin + 10, yPos + 20);

    yPos += 40;

    const prepayRows = [
      ['Prepayment Strategy', data.prepayMode === 'reduceTenure' ? 'Reduce Tenure' : 'Reduce EMI'],
      ['Yearly Prepayment', formatPDFCurrency(data.yearlyPrepay)],
      [data.prepayMode === 'reduceTenure' ? 'Loan Period Reduced By' : 'EMI Reduced To', 
       data.prepayMode === 'reduceTenure' ? `${data.yearsReduced.toFixed(2)} Years` : formatPDFCurrency(data.emiReduced)],
      ['Interest Saved', formatPDFCurrency(data.interestSaved)]
    ];

    pdf.setFontSize(10);
    prepayRows.forEach((row) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(70, 70, 70);
      pdf.text(row[0], margin + 15, yPos);

      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 30, 30);
      pdf.text(row[1], pageWidth - margin - 15, yPos, { align: 'right' });

      yPos += 20;
    });

    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(100, 100, 100);
    pdf.text('[!] Actual savings may vary based on lender policies and prepayment timing.', margin + 15, yPos + 5);

    yPos += 30;
  }

  // ============================================
  // 6. EMI AFFORDABILITY & FOIR (Conditional)
  // ============================================
  if (data.monthlyIncome > 0 && includeAdvancedAnalysis) {
    checkPageBreak(130);

    const income = data.monthlyIncome;
    const emiAmount = data.emi;
    const existingEmis = data.existingEmis || 0;
    const totalEmis = emiAmount + existingEmis;
    let foir = (totalEmis / income * 100);
    const emiRatio = (emiAmount / income * 100).toFixed(1);

    // Add validation for unrealistic FOIR
    let foirStatus = 'Likely Eligible';
    let statusColor = [16, 185, 129]; // Green
    let foirDisplay = foir.toFixed(1) + '%';
    
    if (foir > 100) {
      foirStatus = 'Not Eligible (EMI exceeds income)';
      statusColor = [239, 68, 68]; // Red
      foirDisplay = '>100%';
    } else if (foir > 65) {
      foirStatus = 'High Risk';
      statusColor = [239, 68, 68]; // Red
    } else if (foir > 50) {
      foirStatus = 'Borderline';
      statusColor = [245, 158, 11]; // Amber
    }

    pdf.setFillColor(243, 244, 246); // Light gray background
    pdf.roundedRect(margin, yPos, contentWidth, 110, 5, 5, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text('EMI Affordability & Bank Eligibility (FOIR)', margin + 10, yPos + 20);

    yPos += 40;

    const foirRows = [
      ['Monthly Income', `Rs. ${income.toLocaleString('en-IN')}`],
      ['Existing EMIs', `Rs. ${existingEmis.toLocaleString('en-IN')}`],
      ['New EMI', formatPDFCurrency(data.emi)],
      ['Total EMI Obligations', `Rs. ${Math.round(totalEmis).toLocaleString('en-IN')}`]
    ];

    pdf.setFontSize(10);
    foirRows.forEach((row) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(70, 70, 70);
      pdf.text(row[0], margin + 15, yPos);

      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 30, 30);
      pdf.text(row[1], pageWidth - margin - 15, yPos, { align: 'right' });

      yPos += 18;
    });

    // FOIR with visual indicator and threshold
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(70, 70, 70);
    pdf.text('FOIR (Fixed Obligation to Income Ratio)', margin + 15, yPos);
    
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 30, 30);
    pdf.text(foirDisplay, pageWidth - margin - 15, yPos, { align: 'right' });
    yPos += 20;

    // Status badge with threshold info (no emoji)
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    const statusSymbol = foir <= 50 ? '[OK]' : foir <= 65 ? '[!]' : '[X]';
    pdf.text(`${statusSymbol} Status: ${foirStatus}`, margin + 15, yPos);
    
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(100, 100, 100);
    pdf.text('(Bank limit: <= 50% ideal, <= 65% max)', margin + 150, yPos);

    yPos += 25;
  }

  // ============================================
  // 7. INTEREST RATE SHOCK ANALYSIS (Conditional)
  // ============================================
  if (data.shockDelta > 0 && includeAdvancedAnalysis) {
    checkPageBreak(110);

    pdf.setFillColor(254, 242, 242); // Light red background
    pdf.roundedRect(margin, yPos, contentWidth, 95, 5, 5, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(220, 38, 38); // Red
    pdf.text(`[Interest Rate Shock Analysis +${data.shockDelta}%]`, margin + 10, yPos + 20);

    yPos += 40;

    const shockRows = [
      ['Current EMI', formatPDFCurrency(data.emi)],
      ['New EMI with Rate Shock', formatPDFCurrency(data.shockedEmi)],
      ['EMI Increase', formatPDFCurrency(data.emiIncrease)],
      ['Additional Interest Payable', formatPDFCurrency(data.extraInterest)]
    ];

    pdf.setFontSize(10);
    shockRows.forEach((row) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(70, 70, 70);
      pdf.text(row[0], margin + 15, yPos);

      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 30, 30);
      pdf.text(row[1], pageWidth - margin - 15, yPos, { align: 'right' });

      yPos += 18;
    });

    yPos += 20;
  }

  // ============================================
  // 8. VISUAL SUMMARY (Pie Chart)
  // ============================================
  if (data.chartImage) {
    checkPageBreak(240);

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text('Loan Composition', margin, yPos);
    yPos += 15;
    
    // Add legend before chart for clarity
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(70, 70, 70);
    
    const principalPct = ((data.principal / data.totalAmount) * 100).toFixed(1);
    const interestPct = ((data.totalInterest / data.totalAmount) * 100).toFixed(1);
    
    pdf.setFillColor(102, 126, 234); // Blue
    pdf.rect(margin + 10, yPos, 10, 10, 'F');
    pdf.text(`Principal: ${formatPDFCurrency(data.principal)} (${principalPct}%)`, margin + 25, yPos + 8);
    
    pdf.setFillColor(16, 185, 129); // Green
    pdf.rect(margin + 260, yPos, 10, 10, 'F');
    pdf.text(`Interest: ${formatPDFCurrency(data.totalInterest)} (${interestPct}%)`, margin + 275, yPos + 8);
    
    yPos += 25;

    try {
      pdf.addImage(data.chartImage, 'PNG', margin + 80, yPos, 200, 200);
      yPos += 220;
    } catch (e) {
      console.error('Failed to add chart image:', e);
      pdf.setFontSize(9);
      pdf.setTextColor(150, 150, 150);
      pdf.text('[Chart could not be rendered]', margin + 150, yPos + 50);
      yPos += 80;
    }
  }

  // ============================================
  // 8.3 KEY INSIGHTS (Auto-Generated)
  // ============================================
  checkPageBreak(100);

  pdf.setFillColor(252, 248, 227); // Light cream background
  pdf.roundedRect(margin, yPos, contentWidth, 90, 5, 5, 'F');

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(146, 64, 14); // Brown
  pdf.text('[Key Insights]', margin + 10, yPos + 18);

  yPos += 35;

  // Calculate insights with proper validation
  const principalNum = data.originalPrincipal || data.loanAmount;
  const totalInterestNum = data.totalInterest;
  let interestPercentage = ((totalInterestNum / principalNum) * 100);
  
  // Cap at 999% to prevent display errors
  if (isNaN(interestPercentage) || !isFinite(interestPercentage)) {
    interestPercentage = 0;
  } else {
    interestPercentage = Math.min(999, Math.round(interestPercentage));
  }
  
  const insights = [
    `You will pay ${interestPercentage}% of your loan amount as interest over ${Math.round(data.tenure)} years (Indicative)`
  ];
  
  if (data.yearlyPrepay > 0 && data.interestSaved > 0) {
    const savedLakhs = (data.interestSaved / 100000).toFixed(1);
    insights.push(`Prepaying ${formatPDFCurrency(data.yearlyPrepay)}/year can save ~Rs. ${savedLakhs}L in interest`);
  }
  
  insights.push(`First 5 years contribute ~60% of total interest (front-loaded EMI structure)`);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(70, 70, 70);
  
  insights.forEach((insight, idx) => {
    const bulletPoint = '-'; // Plain dash for compatibility
    pdf.text(`${bulletPoint} ${insight}`, margin + 15, yPos);
    yPos += 16;
  });

  yPos += 15;

  // ============================================
  // 8.5 AMORTIZATION SCHEDULE (Conditional)
  // ============================================
  if (includeAmortization && data.amortizationData && data.amortizationData.length > 0) {
    checkPageBreak(100);

    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text('Amortization Schedule (Yearly Breakdown)', margin, yPos);
    yPos += 20;

    // Table header
    pdf.setFillColor(102, 126, 234);
    pdf.rect(margin, yPos - 15, contentWidth, 25, 'F');
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(255, 255, 255);
    
    const colWidths = [60, 140, 140, 140];
    const colX = [
      margin + 10,
      margin + colWidths[0] + 15,
      margin + colWidths[0] + colWidths[1] + 20,
      margin + colWidths[0] + colWidths[1] + colWidths[2] + 25
    ];
    
    pdf.text('Year', colX[0], yPos);
    pdf.text('Principal Paid', colX[1], yPos);
    pdf.text('Interest Paid', colX[2], yPos);
    pdf.text('Outstanding Balance', colX[3], yPos);
    
    yPos += 25;

    // Table rows
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(30, 30, 30);
    
    data.amortizationData.forEach((row, idx) => {
      if (checkPageBreak(20)) {
        // Redraw header on new page
        pdf.setFillColor(102, 126, 234);
        pdf.rect(margin, yPos - 15, contentWidth, 25, 'F');
        
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(255, 255, 255);
        pdf.text('Year', colX[0], yPos);
        pdf.text('Principal Paid', colX[1], yPos);
        pdf.text('Interest Paid', colX[2], yPos);
        pdf.text('Outstanding Balance', colX[3], yPos);
        
        yPos += 25;
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(30, 30, 30);
      }

      // Alternate row background
      if (idx % 2 === 0) {
        pdf.setFillColor(248, 250, 252);
        pdf.rect(margin, yPos - 13, contentWidth, 18, 'F');
      }

      pdf.setFontSize(9);
      pdf.text(row.year.toString(), colX[0], yPos);
      pdf.text(formatPDFCurrency(row.principal), colX[1], yPos);
      pdf.text(formatPDFCurrency(row.interest), colX[2], yPos);
      pdf.text(formatPDFCurrency(row.balance), colX[3], yPos);

      yPos += 18;
    });

    yPos += 15;
  }

  // ============================================
  // 8.7 INDICATIVE ELIGIBILITY SCORE
  // ============================================
  if (data.monthlyIncome > 0) {
    checkPageBreak(110);

    // Calculate readiness score
    let score = 50; // Base score
    const income = data.monthlyIncome;
    const emiAmount = data.emi;
    const existingEmis = data.existingEmis || 0;
    const totalEmis = emiAmount + existingEmis;
    const foir = (totalEmis / income * 100);
    const emiRatio = (emiAmount / income * 100);
    
    // Score calculation
    if (foir <= 40) score += 20;
    else if (foir <= 50) score += 15;
    else if (foir <= 65) score += 5;
    
    if (emiRatio <= 40) score += 20;
    else if (emiRatio <= 50) score += 10;
    
    if (data.interestType === 'fixed') score += 10;
    
    pdf.setFillColor(240, 253, 244); // Light green background
    pdf.roundedRect(margin, yPos, contentWidth, 100, 5, 5, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(21, 128, 61); // Green
    pdf.text('Indicative Eligibility Score', margin + 10, yPos + 18);
    
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text('(Based on income, FOIR & EMI ratio - non-binding)', margin + 10, yPos + 30);
    
    pdf.setFontSize(24);
    pdf.text(`${score} / 100`, pageWidth - margin - 15, yPos + 32, { align: 'right' });

    yPos += 52;

    // Readiness checklist
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(70, 70, 70);
    
    const checks = [
      { condition: foir <= 50, text: 'FOIR within bank limits' },
      { condition: emiRatio <= 45, text: 'EMI < 45% of income' },
      { condition: data.interestType === 'fixed', text: 'Stable interest structure' }
    ];
    
    checks.forEach((check) => {
      const symbol = check.condition ? '[OK]' : '[X]';
      pdf.setTextColor(check.condition ? 21 : 185, check.condition ? 128 : 28, check.condition ? 61 : 28);
      pdf.text(`${symbol} ${check.text}`, margin + 15, yPos);
      yPos += 14;
    });

    yPos += 20;
  }

  // ============================================
  // 9️⃣ DISCLAIMER (Mandatory)
  // ============================================
  checkPageBreak(110);

  pdf.setFillColor(254, 252, 232); // Light yellow background
  pdf.roundedRect(margin, yPos, contentWidth, 95, 5, 5, 'F');

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(161, 98, 7); // Dark yellow
  pdf.text('[!] Legal Disclaimer', margin + 10, yPos + 18);

  yPos += 32;

  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(70, 70, 70);
  const disclaimerText = `This calculation is indicative and for informational purposes only. Actual EMI, interest rate, and loan terms may vary based on lender policies, your credit profile, and prevailing market conditions. VegakTools does not provide loans or financial advice. Please consult with authorized financial institutions for accurate loan quotes.`;
  const disclaimerLines = pdf.splitTextToSize(disclaimerText, contentWidth - 30);
  pdf.text(disclaimerLines, margin + 15, yPos);

  yPos += 45;

  // Compliance statement
  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(50, 50, 50);
  const complianceText = 'This report is generated using RBI-aligned EMI formulas. No personal data is stored or shared.';
  pdf.text(complianceText, margin + 15, yPos);

  yPos += 20;

  // ============================================
  // 🔟 FOOTER & NEXT STEPS
  // ============================================
  checkPageBreak(100);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(102, 126, 234);
  pdf.text('Next Steps', margin, yPos);
  yPos += 18;

  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  
  const nextSteps = [
    '- Compare offers from RBI-registered banks & NBFCs (No cost, no obligation)',
    '- Check balance transfer benefits for lower interest rates',
    '- Improve EMI affordability through prepayment planning',
    '- Use our SIP Calculator to build prepayment corpus',
    '- Verify final terms with authorized lenders before applying'
  ];

  nextSteps.forEach((step) => {
    pdf.text(step, margin + 10, yPos);
    yPos += 12;
  });

  yPos += 10;
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(102, 126, 234);
  pdf.text('Explore More Tools:', margin, yPos);
  yPos += 14;
  
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(102, 126, 234);
  pdf.textWithLink('Visit: https://vegaktools.com', margin + 10, yPos, {
    url: 'https://vegaktools.com'
  });

  // Add footer to all pages
  const pageCount = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    addFooter(i);
  }

  // Save PDF with loan-type-specific name
  const loanTypeLabel = loanTypeMap[data.loanType] || 'Home Loan';
  const loanTypeSlug = loanTypeLabel
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  const filename = `${loanTypeSlug}-EMI-Calculator-VegakTools.pdf`;
  pdf.save(filename);
}

export async function exportCalculatorPDF(
  rootSelector = '.calculator-container',
  filename = 'emi-summary.pdf',
  options = {}
) {
  const {
    title = 'EMI Calculator Report',
    subtitle = 'VegaKash.AI',
    includeTimestamp = true
  } = options;

  const root = document.querySelector(rootSelector);
  if (!root) throw new Error('Calculator container not found');

  // Build a dedicated, print-friendly container rather than screenshotting interactive UI
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.width = '800px';
  container.style.background = '#ffffff';
  container.style.padding = '16px';
  container.style.fontFamily = 'Inter, system-ui, -apple-system, "Segoe UI", Roboto, Ubuntu, Cantarell, "Noto Sans", sans-serif';

  // Extract key summary values from the existing DOM safely
  const emiEl = root.querySelector('.result-card.highlight .result-value');
  const emiValue = emiEl ? emiEl.textContent.trim() : '';

  const readValueByLabel = (labelText) => {
    const labels = Array.from(root.querySelectorAll('.result-card .result-label'));
    const match = labels.find((l) => (l.textContent || '').includes(labelText));
    if (!match) return '';
    const valEl = match.parentElement?.querySelector('.result-value');
    return valEl ? valEl.textContent.trim() : '';
  };

  const principalValue = readValueByLabel('Principal');
  const interestValue = readValueByLabel('Total Interest');
  const totalValue = readValueByLabel('Total Amount');

  // Header block
  const header = document.createElement('div');
  header.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:12px;">
      <div>
        <div style="font-size:18px;font-weight:800;color:#374151;letter-spacing:-0.2px;">${title}</div>
        <div style="font-size:12px;color:#6b7280;margin-top:2px;">${subtitle}</div>
      </div>
      ${includeTimestamp ? `<div style=\"font-size:11px;color:#9ca3af;\">Generated: ${new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</div>` : ''}
    </div>
    <div style="height:1px;background:#e5e7eb;margin-bottom:12px;"></div>
  `;
  container.appendChild(header);

  // Highlight EMI card
  const highlight = document.createElement('div');
  highlight.setAttribute('style','background:#667eea;color:#ffffff;border-radius:10px;padding:12px;margin-bottom:10px;');
  highlight.innerHTML = `
    <div style="font-size:12px;font-weight:700;opacity:0.9;">Monthly EMI</div>
    <div style="font-size:22px;font-weight:800;letter-spacing:-0.3px;">${emiValue}</div>
  `;
  container.appendChild(highlight);

  // 3-up summary grid
  const grid = document.createElement('div');
  grid.setAttribute('style','display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:12px;');
  function summaryCard(label, value){
    const d = document.createElement('div');
    d.setAttribute('style','background:#ffffff;border:1px solid #e5e7eb;border-radius:10px;padding:10px;');
    d.innerHTML = `<div style="font-size:11px;font-weight:600;color:#6b7280;">${label}</div><div style="font-size:16px;font-weight:700;color:#1f2937;">${value}</div>`;
    return d;
  }
  grid.appendChild(summaryCard('Principal Amount', principalValue));
  grid.appendChild(summaryCard('Total Interest', interestValue));
  grid.appendChild(summaryCard('Total Payable', totalValue));
  container.appendChild(grid);

  // Append for rendering
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false
    });

    const pdf = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 40;
    const contentWidth = pageWidth - 2 * margin;

    // Header
    pdf.setFontSize(20);
    pdf.setTextColor(102, 126, 234);
    pdf.text(title, margin, margin);
    
    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text(subtitle, margin, margin + 20);
    
    if (includeTimestamp) {
      const timestamp = new Date().toLocaleString('en-IN', {
        dateStyle: 'medium',
        timeStyle: 'short'
      });
      pdf.setFontSize(10);
      pdf.text(`Generated: ${timestamp}`, margin, margin + 35);
    }

    // Draw separator line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, margin + 45, pageWidth - margin, margin + 45);

    // Content
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = contentWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let yPosition = margin + 60;

    if (yPosition + imgHeight <= pageHeight - margin) {
      // Fits on one page
      pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
    } else {
      // Multi-page with pagination
      let remainingHeight = imgHeight;
      let srcY = 0;
      let pageNum = 1;

      while (remainingHeight > 0) {
        const availableHeight = pageHeight - yPosition - margin;
        const sliceHeight = Math.min(remainingHeight, availableHeight);
        const sliceRatio = sliceHeight / imgHeight;
        
        pdf.addImage(
          imgData,
          'PNG',
          margin,
          yPosition,
          imgWidth,
          imgHeight,
          '',
          'FAST',
          0,
          -srcY
        );

        // Footer with page number
        pdf.setFontSize(9);
        pdf.setTextColor(150, 150, 150);
        pdf.text(
          `Page ${pageNum} - VegaKash.AI`,
          pageWidth / 2,
          pageHeight - 20,
          { align: 'center' }
        );

        remainingHeight -= availableHeight;
        srcY += availableHeight;

        if (remainingHeight > 0) {
          pdf.addPage();
          yPosition = margin;
          pageNum++;
        }
      }
    }

    pdf.save(filename);
  } finally {
    document.body.removeChild(container);
  }
}
